spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xgsi-customer-portal?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass2000