spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xgsi-customer-portal?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: pass2000
    hikari:
      testOnBorrow: true
      validationQuery: SELECT 1
  jackson:
    serialization:
      fail-on-empty-beans: false